2025-07-07 19:03:41,410:ERROR:search-app:Error occured: 200 is not in list
Traceback (most recent call last):
  File "C:\Users\kleid\Desktop\Coding Factory\Python\cf7-python\chapter05\18_logging\18_logging_app.py", line 28, in main
    index = my_nums.index(num_to_find)
ValueError: 200 is not in list
2025-07-07 19:05:02,646:ERROR:search-app:Error occured: 2.3 is not in list
Traceback (most recent call last):
  File "C:\Users\kleid\Desktop\Coding Factory\Python\cf7-python\chapter05\18_logging\18_logging_app.py", line 29, in main
    index = my_nums.index(num_to_find)
ValueError: 2.3 is not in list
